# Generated by Django 4.0 on 2023-04-09 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_farm_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporter',
            name='ordering',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_farmer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_transporter',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_place', models.CharField(choices=[('IN', 'In Farm'), ('IW', 'In Way'), ('AH', 'At Home')], max_length=5)),
                ('products', models.ManyToManyField(related_name='transportorder', to='api.Order')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportation', to='api.transporter')),
            ],
        ),
    ]
